### ISSUE TITLE
Error when running Si/GaAs examples.

### ISSUE THREAD

**Issue by plasmon1977** [hackingmaterials/amset#138]
Dear Developers,

I have installed the new version of amset, but I met errors when running Si and GaAs examples. I have listed the error messages here. Could you please tell me how to fix this problem? Thank you!

Hao

------------------GaAs: It ran to the end, but error messages appeared.---------------
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ END ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Timing and memory usage:
    ├── interpolation time: 98.3702 s
    ├── dos time: 14.5644 s
    ├── scattering time: 7.0594 s
    ├── transport time: 173.0009 s
    ├── writing time: 0.0019 s
    ├── total time: 293.1251 s
    └── max memory: 6108.3 MB

  amset exiting on 29 May 2020 at 07:57


    ERROR: amset exiting on 29 May 2020 at 07:57
  Traceback (most recent call last):
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/matplotlib/style/core.py", line 114, in use
      rc = rc_params_from_file(style, use_default_template=False)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/matplotlib/__init__.py", line 984, in rc_params_from_file
      config_from_file = _rc_params_in_file(fname, fail_on_error)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/matplotlib/__init__.py", line 914, in _rc_params_in_file
      with _open_file_or_url(fname) as fd:
    File "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/cont
  extlib.py", line 113, in __enter__
      return next(self.gen)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/matplotlib/__init__.py", line 900, in _open_file_or_url
      with open(fname, encoding=encoding) as f:
  FileNotFoundError: [Errno 2] No such file or directory:
  '/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/plot/amset_base.mplstyle'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "GaAs.py", line 32, in <module>
      plt = plotter.get_plot()
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/sumo/plotting/__init__.py", line 60, in wrapper
      matplotlib.pyplot.style.use(list_style)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/matplotlib/style/core.py", line 117, in use
      raise IOError(
  OSError:
  '/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/plot/amset_base.mplstyle' not found in the style
  library and input is not a valid URL or path; see `style.available`
   for list of available styles




------------------------------Si: It failed at the step of calculating transport.----------------------
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ TRANSPORT ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Calculating conductivity, Seebeck, and electronic thermal
  conductivity


    ERROR: amset exiting on 29 May 2020 at 07:47
  Traceback (most recent call last):
    File "Si.py", line 28, in <module>
      amset_data = runner.run()
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/core/run.py", line 68, in run
      mem_usage, (amset_data, usage_stats) = memory_usage(
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/memory_profiler.py", line 343, in memory_usage
      returned = f(*args, **kw)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/core/run.py", line 123, in _run_wrapper
      amset_data, transport_time = self._do_transport(amset_data)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/core/run.py", line 206, in _do_transport
      transport_properties = solve_boltzman_transport_equation(
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/core/transport.py", line 38, in
  solve_boltzman_transport_equation
      sigma, seebeck, kappa = _calculate_transport_properties(
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/amset/core/transport.py", line 189, in
  _calculate_transport_properties
      sigma[n, t], seebeck[n, t], kappa[n, t], _ =
  calc_Onsager_coefficients(
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/BoltzTraP2/bandlib.py", line 492, in
  calc_Onsager_coefficients
      pL11 = np.linalg.pinv(L11[iT, imu])
    File "<__array_function__ internals>", line 5, in pinv
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/numpy/linalg/linalg.py", line 1961, in pinv
      u, s, vt = svd(a, full_matrices=False, hermitian=hermitian)
    File "<__array_function__ internals>", line 5, in svd
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/numpy/linalg/linalg.py", line 1626, in svd
      u, s, vh = gufunc(a, signature=signature, extobj=extobj)
    File
  "/public/home/hao/.conda/envs/my_pymatgen/lib/python3.8/site-
  packages/numpy/linalg/linalg.py", line 106, in
  _raise_linalgerror_svd_nonconvergence
      raise LinAlgError("SVD did not converge")
  numpy.linalg.LinAlgError: SVD did not converge

**Comment by utf** [comment]
Hi @plasmon1977, thanks for raising this issue.

I've just pushed some fixes to the GitHub repository. Can you try updating your installation and trying the examples again.

Thanks!

- Alex

**Comment by kcbhamu** [comment]
Dear Developer, do you have any plan to implement AMSET for Quantum Espresso?

**Comment by utf** [comment]
Hi @kcbhamu,

There are currently no plans to implement AMSET for Quantum Espresso. Theoretically this shouldn't be too hard but it would require writing a Python interface for reading the electronic wave functions. If there is sufficient interest in this, then I may look into it in the future.

Best,
Alex

**Comment by kcbhamu** [comment]
Yes, I am a QE user and I see from the forum that many people are looking for this kind of tools.
