### ISSUE TITLE
Error in defromation potential extraction in 0.3.1 version

### ISSUE THREAD

**Issue by akentphonon** [hackingmaterials/amset#255]
Dear Developer,

Thank you for this wonderful code.

After upgrading the amset to recent release (0.3.1) I get the following error in deformation potential extraction step (amset deform read).   The older version worked fine for the same system. 

Traceback (most recent call last):
  File "/home/alex/.local/bin/amset", line 8, in <module>
    sys.exit(cli())
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/alex/.local/lib/python3.6/site-packages/amset/tools/deformation.py", line 188, in read
    if "bands" in kwargs and kwargs["ibands"] is not None:
KeyError: 'ibands'

Any insights will be helpful.

One more on related noted: (This is not tested on recent version- as for me deform read step does not work)

 When I try to extract deformation for a 2D materials- if I use say n x n x 1 k-grid, the "amset deform read" throws out an error.  It only works if I use finite kpoints along z direction such as n x n x 2 k-grid. Not sure why there need to be finite k-mesh in all three directions.

Any thoughts  on these will be helpful.

Best,
Alex kent

**Comment by utf** [comment]
Hi Alex,

Thanks for raising these issues. I've just released a new version that should fix your first problem.

As for the second one, I have an idea what the problem could be. I've just pushed a fix for this to GitHub (not to Pypi), so if you try installing from source and letting me know if this fixes your problem that would be great.

If it doesn't fix it, please can you post your error message here.

Best,
Alex

**Comment by akentphonon** [comment]
Thank you so much Alex.

I mirrored the github repo and both issued are fixed. :)

Best,
AK

**Comment by utf** [comment]
Fantastic. Thanks for checking. I will push a new release for the 2D materials fix also.
