### ISSUE TITLE
TypeError when running the example

### ISSUE THREAD

**Issue by plasmon1977** [hackingmaterials/amset#51]
Dear amset users,

How to fix the TypeError like below. Thank you!

[root@admin GaAs]# python GaAs.py
/public/software/anaconda3/lib/python3.6/site-packages/pymatgen/io/vasp/outputs.py:886: UserWarning: No POTCAR file with matching TITEL fields was found in /public/src/phys/amset/test_files/GaAs_mp-2534
  " was found in {}".format(os.path.abspath(p)))
2019-06-05 19:23:24 INFO     bs_is_isotropic: True
2019-06-05 19:23:24 DEBUG    n-Ecut: 0.258519909 eV

2019-06-05 19:23:24 DEBUG    p-Ecut: 0.17234660599999999 eV

Traceback (most recent call last):
  File "GaAs.py", line 41, in <module>
    temperatures=[300, 600],
  File "/public/software/anaconda3/lib/python3.6/site-packages/amset-0.1.0-py3.6.egg/amset/core.py", line 326, in from_vasprun
    return Amset(band_structure, num_electrons, material_params, **kwargs)
  File "/public/software/anaconda3/lib/python3.6/site-packages/amset-0.1.0-py3.6.egg/amset/core.py", line 263, in __init__
    interpolation_type=interpolation)
  File "/public/software/anaconda3/lib/python3.6/site-packages/amset-0.1.0-py3.6.egg/amset/interpolate/__init__.py", line 52, in get_interpolater
    return BoltzTraP2Interpolater(band_structure, num_electrons)
  File "/public/software/anaconda3/lib/python3.6/site-packages/amset-0.1.0-py3.6.egg/amset/interpolate/boltztrap2.py", line 40, in __init__
    band_structure, num_electrons, **kwargs)
  File "/public/software/anaconda3/lib/python3.6/site-packages/amset-0.1.0-py3.6.egg/amset/interpolate/base.py", line 47, in __init__
    self.initialize()
  File "/public/software/anaconda3/lib/python3.6/site-packages/amset-0.1.0-py3.6.egg/amset/interpolate/boltztrap2.py", line 53, in initialize
    magmom=None)
TypeError: get_equivalences() got an unexpected keyword argument 'magmom'

**Comment by utf** [comment]
It looks like your BoltzTraP2 installation might be out of date. Can you try installing the latest version and re-running?

**Comment by plasmon1977** [comment]
Thank you! I installed BoltzTraP2-19.1.1 and the above TypeError disappeared. Now I met some new error information
/public/software/anaconda3/lib/python3.6/site-packages/pymatgen/io/vasp/outputs.py:886: UserWarning: No POTCAR file with matching TITEL fields was found in /public/src/phys/amset/test_files/PbTe_mp-19717
  " was found in {}".format(os.path.abspath(p)))
2019-06-06 08:55:50 INFO     bs_is_isotropic: True
2019-06-06 08:55:50 DEBUG    n-Ecut: 0.17234660599999999 eV

2019-06-06 08:55:50 DEBUG    p-Ecut: 0.258519909 eV

Traceback (most recent call last):
  File "PbTe.py", line 33, in <module>
    amset.run_profiled(coeff_file=coeff_file, kgrid_tp="coarse")
TypeError: run_profiled() got an unexpected keyword argument 'coeff_file'

**Comment by plasmon1977** [comment]
Thank you! I have fixed this problem by installing a new version of
BoltzTraP2. But I met a new problem, which has been posted on Github.
Could you please tell me how to fix this new problem? Thank you!

Best,
Hao

Alex Ganose <notifications@github.com> 于2019年6月6日周四 上午12:15写道：
