### ISSUE TITLE
ValueError: Could not find fermi within low concentration

### ISSUE THREAD

**Issue by thienbinh92** [hackingmaterials/amset#852]
I tried GaAs example. I found that the experiment's intrinsic carrier concentration is just 1.7e6. But if I reduce the doping concentration to 1.7e6, the following error appears. Is the method not suitable for low doping content or semiconductors?
```
  Traceback (most recent call last):
    File "~/miniconda3/lib/python3.9/site-packages/amset/core/data.py", line 219, in 
  set_doping_and_temperatures
   ) = self.dos.get_fermi(
    File "~/miniconda3/lib/python3.9/site-packages/amset/electronic_structure/dos.py", line 224, in get_fermi raise ValueError(

  ValueError: Could not find fermi within 100.0% of 
  concentration=2.652506335351714e-19
```

**Comment by utf** [comment]
I have never heard of carrier concentrations that low before. For GaAs you typically see concentrations from 1e13 and above. 

Could there be a mistake with your units? The concentration should be in cm^-3.

**Comment by thienbinh92** [comment]
I thought about a low doping concentration because if I set the doping concentration of -3e13, the obtained average electronic conductivity is very much higher compared with the experimental one (1e-6 to 1e-8 /ohm cm). I got information from [GaAs](https://www.azom.com/article.aspx?ArticleID=8349): "_Intrinsic Carrier Concentration | 1.79 x 106 cm-3_". I also found a higher doping concentration in another document (1e13~1e14), but don't know the reasonable one. Maybe a range of doping concentrations is needed. Is it fine?
```
  Average conductivity (σ), Seebeck (S) and mobility (μ) results:

    conc [cm-3]    temp [K]    σ [S/m]    S [µV/K]    μ [cm2/Vs]
  -------------  ----------  ---------  ----------  ------------
      -3.00e+13       201.0   1.72e+01   -8.56e+02       35825.3
      -3.00e+13       290.0   7.78e+00   -9.11e+02       16187.2
      -3.00e+13       401.0   4.18e+00   -9.67e+02        8705.5
      -3.00e+13       506.0   2.81e+00   -1.01e+03        5836.5
      -3.00e+13       605.0   2.81e+00   -9.84e+02        4387.0
      -3.00e+13       789.0   3.10e+01   -7.11e+02        2906.5
      -3.00e+13       994.0   2.40e+02   -5.45e+02        1989.5
```
